version: '3.7'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: bash -c "npm run dev"
    ports:
      - "3000:3000"
    volumes:
     - .:/app
  build:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: npm run build
    volumes:
     - .:/app
  npm:
    environment:
      - GIT_SSH_COMMAND
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
     - .:/app
     - ~/.ssh:/root/.ssh
